[[redirects]]
  from = "http://flaprimo.netlify.com/*"
  to = "https://flavioprimo.xyz/:splat"

[[redirects]]
  from = "https://flaprimo.netlify.com/*"
  to = "https://flavioprimo.xyz/:splat"

[[redirects]]
  from = "/programming-languages/*"
  to = "/blog/:splat"

[[redirects]]
  from = "/arduino/*"
  to = "/blog/:splat"

[[redirects]]
  from = "/os/windows/*"
  to = "/blog/:splat"

[[redirects]]
  from = "/os/*"
  to = "/blog/:splat"

[[redirects]]
  from = "/university/*"
  to = "/blog/:splat"

[[plugins]]
package = "netlify-plugin-gatsby-cache"